apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: durellirsd/spring-boot-log:v02
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-logs # shared space monitored with Promtail
              mountPath: /app/logs
        # Sidecar Container Promtail
        - name: promtail
          image: grafana/promtail:master
          args:
            - "-config.file=/etc/promtail/promtail.yaml" # Found in the ConfigMap
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: shared-logs # shared space
              mountPath: /app/logs
      volumes:
        - name: config
          configMap:
            name: promtail-sidecar-config-map
        - name: shared-logs  # shared space monitored with Promtail
          emptyDir: